#!/bin/sh
# Start Gnome 3 Desktop 
# [ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
# [ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
# vncconfig -iconic &
# dbus-launch --exit-with-session gnome-session &
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
exec startxfce4 &
xterm -e  "~/.vnc/startup_abc.sh"
